language: node_js
node_js:
- '8'
- '6'
- '10'
- stable
sudo: false
before_install:
- export PATH=$PATH:`yarn global bin`
- yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: 2SiYo97hTv1hR0dT63fg4s2h0yRDCaOyRgYIzuAhywaYqIPpQGytuJL+FcTdnMdqLYs913qO9gmoGCxGXr+dErs/X2FEau2YdqzmV2ZNDEemWyY8uaxOJ6ey4A1nDvoYkRb/fFWEdTjQwr2G10KVqxp0+S4+AXrJ76FGXBMmlcFJrPAAptXV2arOiZSOZs3CDjRKqPiXkfRrrBUi2WSI/S5EiMPF1IuIOfZcJMCFyS511+13ahLPT8QNnd+tf7ZATswnpcbXcPDgbIwNdaFKqdnlMDmQ/4z/61q7ZaWekBEe1Qq1JvYSOntlkyutoTH0q5MOQyBh5PTMPGsvnImhl+d4QcocWNb5TndrLlvRMl/7HoVKyGFLCknLqtyoB5unfcre9X8JamLg4Ci49ZrxAv8oswLMoOsVH/9VRmBE0Kb0UJtsPGx5SbrOFgy9D5tHpHn/iW2DfDZzjpq1yOgZC3+XIiPk5NaPknUNkLYeviFdTt45+tJhz26xMNmMSGsS6WpGqhQBDgGglxRVhgJCvIR4gBLMKAqqfMjb/qTVnL7OrFEQqvrfb5O3gOG3Lb47BvSvSTBaJ1V+h0IjydwveH/zOqC6w4lnGxmKX268vgMglSRtIKsIDgLyCyBpa0Mk0kBuRoj+OAzWQr+DzO4f62EbJ7CG6CtTd4EffrfZJi4=
